spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-production-db-host:3306/group_study_prod?serverTimezone=UTC&characterEncoding=UTF-8
    username: prod_user
    password: secure_password
  thymeleaf:
    cache: true
  sql:
    init:
      mode: never

logging:
  level:
    com.groupstudy: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
  file:
    name: /var/log/group-study/application.log
    max-size: 10MB
    max-history: 30

# 운영 환경 보안 설정
server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: your_keystore_password
    key-store-type: PKCS12
  servlet:
    session:
      cookie:
        secure: true
        http-only: true